// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn9XRAQqLD8OgQzXPTCxjeI8MwhYLREO4',
    appId: '1:533108761673:web:d6664cbf5c10adfe84cb98',
    messagingSenderId: '533108761673',
    projectId: 'jaytest-689b8',
    authDomain: 'jaytest-689b8.firebaseapp.com',
    storageBucket: 'jaytest-689b8.firebasestorage.app',
    measurementId: 'G-JTB5K2DH3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARr6yvLWSE7RNXckW23YauSrPSViEEXn0',
    appId: '1:533108761673:android:f93831b71b10239284cb98',
    messagingSenderId: '533108761673',
    projectId: 'jaytest-689b8',
    storageBucket: 'jaytest-689b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABbPWN5YSJr4U5eWt52MDP38F2F1y6g1E',
    appId: '1:533108761673:ios:98ef95a20150c2cd84cb98',
    messagingSenderId: '533108761673',
    projectId: 'jaytest-689b8',
    storageBucket: 'jaytest-689b8.firebasestorage.app',
    iosBundleId: 'com.example.jay',
  );

}